// This file contains placeholder data
const services = require('./services.json');

const { v4: uuidv4 } = require('uuid');

const generateUUID = function () {
  return uuidv4();
};

const getAmount = function () {
  const totalAmount =
    services['Living Room Areas'].cost +
    services['Kitchen'].cost +
    this.bath_rooms * services['Bedrooms'].cost +
    this.bath_rooms * services['Bathrooms'].cost +
    (this.laundry_and_ironing === true
      ? services['Laundry & Ironing'].cost
      : 0) +
    (this.oven === true ? services['Oven'].cost : 0) +
    (this.fridge === true ? services['Fridge'].cost : 0) +
    (this.cabinets === true ? services['Cabinets'].cost : 0);
  return Number(totalAmount);
};

const users = [
  // {
  //   id: generateUUID(),
  //   name: 'Thando',
  //   email: 'thando@brightbroom.com',
  //   password: '123456',
  //   email_verified: '2024-05-20',
  //   image_url: '/users/thando-somacele.png',
  //   contact_number: '+27 072-225-1491',
  //   address: '123 Main Street, Johannesburg, South Africa',
  // },
  {
    id: generateUUID(),
    name: 'Mthi',
    email: 'thando.somacele@gmail.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/thando-somacele.png',
    contact_number: '+27 072-225-1493',
    address: '123 Main Street, Johannesburg, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Delba de',
    email: 'delba@oliveira.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/delba-de-oliveira.png',
    contact_number: '+27 123-456-7890',
    address: '123 Main Street, Johannesburg, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Lee',
    email: 'lee@robinson.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/lee-robinson.png',
    contact_number: '+27 223-456-7890',
    address: '456 Side Street, Cape Town, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Hector',
    email: 'hector@simpson.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/hector-simpson.png',
    contact_number: '+27 323-456-7890',
    address: '789 South Street, Durban, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Steven',
    email: 'steven@tey.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/steven-tey.png',
    contact_number: '+27 423-456-7890',
    address: '123 North Street, Pretoria, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Steph',
    email: 'steph@dietz.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/steph-dietz.png',
    contact_number: '+27 523-456-7890',
    address: '456 West Street, Bloemfontein, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Michael',
    email: 'michael@novotny.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/michael-novotny.png',
    contact_number: '+27 623-456-7890',
    address: '789 East Street, Port Elizabeth, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Good',
    email: 'good@rabbit.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/good-rabbit.png',
    contact_number: '+27 723-456-7890',
    address: '123 West Street, Durban, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Emil',
    email: 'emil@kowalski.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/emil-kowalski.png',
    contact_number: '+27 823-456-7890',
    address: '456 North Street, Johannesburg, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Amy',
    email: 'amy@burns.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/amy-burns.png',
    contact_number: '+27 923-456-7890',
    address: '789 South Street, Cape Town, South Africa',
  },
  {
    id: generateUUID(),
    name: 'Balazs',
    email: 'balazs@orban.com',
    password: '123456',
    email_verified: '2024-05-20',
    image_url: '/users/balazs-orban.png',
    contact_number: '+27 1023-456-7890',
    address: '123 East Street, Pretoria, South Africa',
  },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  // { month: 'Dec', revenue: 4800 },
];

const cleaners = [
  {
    id: generateUUID(),
    name: 'Nandi',
    home_address: '80 First Avenue, Cosmo City, South Africa',
    contact_number: '+27 087-361-6186',
    email: 'nandi.nkosi@shineandsparkle.co.za',
    national_id: 'A399012',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/nandi-nkosi.png',
  },
  {
    id: generateUUID(),
    name: 'Kudzai',
    home_address: '12 Market Street, Deepsloot, South Africa',
    contact_number: '+27 083-896-8976',
    email: 'kudzai.mkhize@cleanbright.com',
    national_id: 'B221325',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/kudzai-mkhize.png',
  },
  {
    id: generateUUID(),
    name: 'Sipho',
    home_address: '91 Liberty Road, Cosmo City, South Africa',
    contact_number: '+27 084-113-8950',
    email: 'sipho.moyo@cleanbright.com',
    national_id: '7401154712038',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/sipho-moyo.png',
  },
  {
    id: generateUUID(),
    name: 'Tatenda',
    home_address: '83 Main Road, Deepsloot, South Africa',
    contact_number: '+27 085-419-4306',
    email: 'tatenda.masuku@neatfreaks.org',
    national_id: 'C245274',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/tatenda-masuku.png',
  },
  {
    id: generateUUID(),
    name: 'Thabo',
    home_address: '68 Second Avenue, Deepsloot, South Africa',
    contact_number: '+27 088-855-7905',
    email: 'thabo.ncube@shineandsparkle.co.za',
    national_id: '6711046209129',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/thabo-ncube.png',
  },
  {
    id: generateUUID(),
    name: 'Nomvula',
    home_address: '29 First Avenue, Deepsloot, South Africa',
    contact_number: '+27 081-615-5400',
    email: 'nomvula.ncube@dustaway.net',
    national_id: 'B581117',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/nomvula-ncube.png',
  },
  {
    id: generateUUID(),
    name: 'Sipho',
    home_address: '7 Liberty Road, Deepsloot, South Africa',
    contact_number: '+27 084-676-8537',
    email: 'sipho.phiri@shineandsparkle.co.za',
    national_id: 'C713914',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/sipho-phiri.png',
  },
  {
    id: generateUUID(),
    name: 'Tendai',
    home_address: '97 Market Street, Cosmo City, South Africa',
    contact_number: '+27 087-742-3848',
    email: 'tendai.khumalo@cleanbright.com',
    national_id: 'B996983',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/tendai-khumalo.png',
  },
  {
    id: generateUUID(),
    name: 'Nomvula',
    home_address: '7 Liberty Road, Deepsloot, South Africa',
    contact_number: '+27 081-572-9147',
    email: 'nomvula.nkosi@shineandsparkle.co.za',
    national_id: '7306195810119',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/nomvula-nkosi.png',
  },
  {
    id: generateUUID(),
    name: 'Thabo',
    home_address: '17 Liberty Road, Deepsloot, South Africa',
    contact_number: '+27 082-270-5585',
    email: 'thabo.ncube@neatfreaks.org',
    national_id: '6810266071099',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/thabo-ncube.png',
  },
  {
    id: generateUUID(),
    name: 'Palesa',
    home_address: '54 Market Street, Deepsloot, South Africa',
    contact_number: '+27 082-303-4280',
    email: 'palesa.moyo@dustaway.net',
    national_id: '8503164568198',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/palesa-moyo.png',
  },
  {
    id: generateUUID(),
    name: 'Lerato',
    home_address: '23 Liberty Road, Riverside in Midrand, South Africa',
    contact_number: '+27 089-164-9038',
    email: 'lerato.ncube@dustaway.net',
    national_id: '9709154859119',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/lerato-ncube.png',
  },
  {
    id: generateUUID(),
    name: 'Lerato',
    home_address: '45 Liberty Road, Deepsloot, South Africa',
    contact_number: '+27 088-121-2858',
    email: 'lerato.mkhize@shineandsparkle.co.za',
    national_id: 'B985704',
    country_of_origin: 'Zimbabwe',
    image_url: '/cleaners/lerato-mkhize.png',
  },
  {
    id: generateUUID(),
    name: 'Zukisa',
    home_address: '12 Liberty Road, Deepsloot, South Africa',
    contact_number: '+27 083-300-4734',
    email: 'zukisa.moyo@dustaway.net',
    national_id: '8311163300138',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/palesa-moyo.png',
  },
  {
    id: generateUUID(),
    name: 'Tendai',
    home_address: '12 Main Road, Cosmo City, South Africa',
    contact_number: '+27 085-928-9805',
    email: 'tendai.ncube@dustaway.net',
    national_id: '9410167146138',
    country_of_origin: 'South Africa',
    image_url: '/cleaners/tendai-ncube.png',
  },
];

// users.forEach((user) => {
//   user.id = user.generateUUID();
// });

// cleaners.forEach((cleaner) => {
//   cleaner.id = cleaner.generateUUID();
// });

const bookings = [
  {
    id: generateUUID(),
    user_id: users[0].id,
    user_name: 'Thando',
    email: 'tsomacele@gmail.com',
    contact_number: '+27 072-225-1491',
    address: '123 Main Street, Johannesburg, South Africa',
    bed_rooms: 3,
    bath_rooms: 2,
    laundry_and_ironing: true,
    oven: false,
    fridge: true,
    cabinets: false,
    total_hours: 5,
    getAmount,
    service_date: '2024-05-20',
    service_time: '2024-05-20T09:00',
    status: 'completed',
    cleaner_id: cleaners[0].id,
  },
  {
    id: generateUUID(),
    user_id: users[3].id,
    user_name: 'Lee',
    email: 'lee@robinson.com',
    contact_number: '+27 223-456-7890',
    address: '456 Side Street, Cape Town, South Africa',
    bed_rooms: 2,
    bath_rooms: 1,
    laundry_and_ironing: false,
    oven: true,
    fridge: false,
    cabinets: true,
    total_hours: 4,
    getAmount,
    service_date: '2024-05-21',
    service_time: '2024-05-21T10:00',
    status: 'completed',
    cleaner_id: cleaners[0].id,
  },
  {
    id: generateUUID(),
    user_id: users[0].id,
    user_name: 'Hector',
    email: 'hector@simpson.com',
    contact_number: '+27 323-456-7890',
    address: '789 South Street, Durban, South Africa',
    bed_rooms: 4,
    bath_rooms: 3,
    laundry_and_ironing: true,
    oven: false,
    fridge: true,
    cabinets: false,
    total_hours: 6,
    getAmount,
    service_date: '2024-05-22',
    service_time: '2024-05-22T11:00',
    status: 'completed',
    cleaner_id: cleaners[3].id,
  },
  {
    id: generateUUID(),
    user_id: users[6].id,
    user_name: 'Steven',
    email: 'steven@tey.com',
    contact_number: '+27 423-456-7890',
    address: '123 North Street, Pretoria, South Africa',
    bed_rooms: 1,
    bath_rooms: 1,
    laundry_and_ironing: false,
    oven: true,
    fridge: false,
    cabinets: true,
    total_hours: 3,
    getAmount,
    service_date: '2024-05-23',
    service_time: '2024-05-23T12:00',
    status: 'completed',
    cleaner_id: cleaners[4].id,
  },
  {
    id: generateUUID(),
    user_id: users[2].id,
    user_name: 'Steph',
    email: 'steph@dietz.com',
    contact_number: '+27 523-456-7890',
    address: '456 West Street, Bloemfontein, South Africa',
    bed_rooms: 5,
    bath_rooms: 4,
    laundry_and_ironing: true,
    oven: false,
    fridge: true,
    cabinets: false,
    total_hours: 8,
    getAmount,
    service_date: '2024-05-24',
    service_time: '2024-05-24T13:00',
    status: 'completed',
    cleaner_id: cleaners[5].id,
  },
  {
    id: generateUUID(),
    user_id: users[0].id,
    user_name: 'Michael',
    email: 'michael@novotny.com',
    contact_number: '+27 623-456-7890',
    address: '789 East Street, Port Elizabeth, South Africa',
    bed_rooms: 2,
    bath_rooms: 2,
    laundry_and_ironing: false,
    oven: true,
    fridge: false,
    cabinets: true,
    total_hours: 4,
    getAmount,
    service_date: '2024-05-25',
    service_time: '2024-05-25T14:00',
    status: 'pending',
    cleaner_id: cleaners[2].id,
  },
  {
    id: generateUUID(),
    user_id: users[0].id,
    user_name: 'Good',
    email: 'good@rabbit.com',
    contact_number: '+27 723-456-7890',
    address: '123 West Street, Durban, South Africa',
    bed_rooms: 3,
    bath_rooms: 3,
    laundry_and_ironing: true,
    oven: false,
    fridge: true,
    cabinets: false,
    total_hours: 5,
    getAmount,
    service_date: '2024-05-26',
    service_time: '2024-05-26T15:00',
    status: 'booked',
    cleaner_id: cleaners[7].id,
  },
  {
    id: generateUUID(),
    user_id: users[4].id,
    user_name: 'Emil',
    email: 'emil@kowalski.com',
    contact_number: '+27 823-456-7890',
    address: '456 North Street, Johannesburg, South Africa',
    bed_rooms: 4,
    bath_rooms: 4,
    laundry_and_ironing: false,
    oven: true,
    fridge: false,
    cabinets: true,
    total_hours: 6,
    getAmount,
    service_date: '2024-05-27',
    service_time: '2024-05-27T16:00',
    status: 'booked',
    cleaner_id: cleaners[7].id,
  },
  {
    id: generateUUID(),
    user_id: users[2].id,
    user_name: 'Amy',
    email: 'amy@burns.com',
    contact_number: '+27 923-456-7890',
    address: '789 South Street, Cape Town, South Africa',
    bed_rooms: 5,
    bath_rooms: 5,
    laundry_and_ironing: true,
    oven: false,
    fridge: true,
    cabinets: false,
    total_hours: 8,
    getAmount,
    service_date: '2024-05-28',
    service_time: '2024-05-28T17:00',
    status: 'started',
    cleaner_id: cleaners[0].id,
  },
  {
    id: generateUUID(),
    user_id: users[0].id,
    user_name: 'Balazs',
    email: 'balazs@orban.com',
    contact_number: '+27 1023-456-7890',
    address: '123 East Street, Pretoria, South Africa',
    bed_rooms: 3,
    bath_rooms: 2,
    laundry_and_ironing: false,
    oven: true,
    fridge: false,
    cabinets: true,
    total_hours: 5,
    getAmount,
    service_date: '2024-05-29',
    service_time: '2024-05-29T18:00',
    status: 'started',
    cleaner_id: cleaners[3].id,
  },
];

bookings.forEach((booking) => {
  // booking.id = booking.generateUUID();
  booking.amount = booking.getAmount();
});

module.exports = {
  users,
  revenue,
  cleaners,
  bookings,
};
